// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EditHosts(arg1) {
  return window['go']['services']['hostsService']['EditHosts'](arg1);
}

export function GetHostsBackupFilePaths() {
  return window['go']['services']['hostsService']['GetHostsBackupFilePaths']();
}

export function ReadHosts() {
  return window['go']['services']['hostsService']['ReadHosts']();
}
