// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EditHosts(arg1:string):Promise<string>;

export function GetHostsBackupFilePaths():Promise<Array<string>>;

export function ReadHosts():Promise<string>;
