// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Alert(arg1, arg2) {
  return window['go']['main']['App']['Alert'](arg1, arg2);
}

export function Confirm(arg1, arg2) {
  return window['go']['main']['App']['Confirm'](arg1, arg2);
}

export function GetCtx() {
  return window['go']['main']['App']['GetCtx']();
}

export function RequestUrl(arg1) {
  return window['go']['main']['App']['RequestUrl'](arg1);
}
