// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Alert(arg1:string,arg2:string):Promise<void>;

export function Confirm(arg1:string,arg2:string):Promise<string>;

export function GetCtx():Promise<context.Context>;

export function RequestUrl(arg1:string):Promise<string>;
